---
apiVersion: v1
kind: Namespace
metadata:
  name:  ct-dummy-dev
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ct-dummy-pvc
#   namespace: ct-dummy-dev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-dummy
  namespace: ct-dummy-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ct-dummy
  template:
    metadata:
      labels:
        app: ct-dummy
        terraform: "false"
    spec:
      # volumes:
      #   - name: log-pvc
      #     persistentVolumeClaim:
      #       claimName: ct-dummy-pvc
      containers:
      - name: ct-dummy
        image: klimdos/python-flask-dummy
        env:
          - name: PORT
            value: "8000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        # volumeMounts:
        # - mountPath: /opt/logs
        #   name: log-pvc
---
kind: Service
apiVersion: v1
metadata:
  name:  ct-dummy-svc
  namespace: ct-dummy-dev
  labels:
    role: web
    dns: route53
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: name=ct-dummy-dev, terraform=false
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: ct-dummy
  type: NodePort
  ports:
  - name:  ui
    port:  80
    targetPort:  8000
    nodePort: 30080
