---
- name: Add gpg keys for docker and kubernetes repos
  apt_key:
    url: "{{ item }}"
  loop:
   - https://download.docker.com/linux/ubuntu/gpg
   - https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add docker and kubernetes repos 
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
  loop:
    - {repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable", filename: "docker"}
    - {repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main", filename: "kubernetes"}

- name: Install stuff
  apt:
    pkg:
      - docker-ce=18.06.1~ce~3-0~ubuntu 
      - kubelet=1.13.5-00 
      - kubeadm=1.13.5-00 
      - kubectl=1.13.5-00